### ISSUE TITLE
Screen art

### ISSUE THREAD

**Issue by erikhallin** [dguise/ld42#12]
Vid satr visas startskärm, sedan instructions, därefter börjar spelet. Vid game over visas gameover screen. Vid knapptryckning går man till nästa state, dvs från startskärm till instruktions, till game och från game over till startskärm efter en reset av allt.

Rita: startskärm, instructions, gameover

- [x] Art startskärm
- [x] Art instructions
- [x] Art gameover? (jag tycker gameover-scenen är good enough :triumph:)

- [x] Lägga in startbild i 1_StartScreen
- [x] Lägga in instructions 2_InfoScreen
- [x] Skapa & Lägga in gameover i 5_WinScreen som också måste kallas vid win?

**Comment by maakep** [comment]
Blev detta inlagd igår? Art är gjort? 

Gameover ska vara när man vinner va? Inte när man förlorar (då startar man bara om).

Den som gör Win Screen kan ju lägga in den där esc to quit, space/mouse to replay som finns på i DeathScreenManager

**Comment by erikhallin** [comment]
Allt programmerande görs av dig, om du inte gjort har det inte gjorts. Alex/Per fokuserar på tweaks/polering. Jag har ritat allt som ska ritas, finns i slack

**Comment by maakep** [comment]
Alright, jag är nog hemma vid 18 ikväll + städa&äta, men kan nog äta vid
datorn och städa går rätt fort.
