### ISSUE TITLE
Win scenario

### ISSUE THREAD

**Issue by erikhallin** [dguise/ld42#14]
När man når slutet av banan vinner man...
Visa win-screen, vid knapptryck resetas spelet och går till startscreen.
"Congratulations, you reached the end of space. And what happens there we do not really know..."

**Comment by maakep** [comment]
Ska det verkligen finnas win condition? Endless runner?

**Comment by erikhallin** [comment]
1. tror de flesta blir grada av att "vinna", kan inte vara för långt. 
2. Kräver random generation design och har inte samma leveldesignmöjligheter.

**Comment by maakep** [comment]
1. Okej, kan köpa det.
2. Mja, kan ju göra en lång level och sen bara copy-pasta den en 10 20 ggr. Alternativt lägga en trigger som teleporterar tillbaka en till början.

Men jag håller med på 1, jag tycker också vi kör med win condition. Har det lagts in? Magnus sa att han klarade leveln, vilket får mig att tro det finns win condition. @ProgHaj @UrbanHelsing @erikhallin ?

**Comment by erikhallin** [comment]
Ska bara visa en screen, screen finns och lagd i slack. efter knapptryckning restartas spelet
