### ISSUE TITLE
Fuel canister HUD

### ISSUE THREAD

**Issue by erikhallin** [dguise/ld42#8]
Visa små 2D sprites för hur många fuel canisters man har.
Tags bort om man gör en spacebar boost.
Lägg till 3 nya vid pickup av fuel-canister.

**Comment by maakep** [comment]
Om man har 5 st fuel, och bilden för fuel är 🌮, ska det vara:

5x 🌮 

eller

🌮 🌮 🌮 🌮 🌮 

?

**Comment by maakep** [comment]
Eller kanske är det en HUD som följer efter spelaren?

**Comment by erikhallin** [comment]
Ska vara taco taco taco taco taco, och inte 5x taco

**Comment by erikhallin** [comment]
hud statiskt på skärmen, nere till vänster och expanderar höger. följer ej med spelaren

**Comment by maakep** [comment]
@UrbanHelsing behöver bild för fuel HUD
